#!/bin/sh
set -eu

MAJOR=1
MINOR=0
BUILD=$(($(git rev-list --count HEAD) + 1))
VERSION="$MAJOR.$MINOR.$BUILD"

cat > version.py <<EOF
MAJOR = $MAJOR
MINOR = $MINOR
BUILD = $BUILD

VERSION = "$VERSION"
EOF

git add version.py
echo "Updated version.py to $VERSION"
