from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from version import VERSION


DEFAULT_INPUT = Path(
    r"C:\Users\j.arvanitis\Desktop\Tango\Logs\audit.OPNBISOBKT01.2026-03-06"
)
DEFAULT_OUTPUT = Path(r"C:\Users\j.arvanitis\Desktop\Tango\Logs\LogComparator")
APP_VERSION = VERSION
APP_AUTHOR = "IARV"
DEFAULT_HOST = "10.1.110.84"
DEFAULT_USER = "j.arvanitis"
DEFAULT_SUDO_PASSWORD = "12345ja!@#$%"
REMOTE_LOG_DIR = "/opt/tango/MLNPSP01/log"
REMOTE_AUDIT_DIR = "/opt/tango/MLNPSP01/audit"
SSH_PORT = 22
SSH_TIMEOUT = 10
SEPARATOR_PREFIX = "=" * 40
CORRELATION_WINDOW_SECONDS = 5 * 60


@dataclass
class RuntimeSettings:
    output: Path = DEFAULT_OUTPUT
    user: str = DEFAULT_USER
    sudo_password: str = DEFAULT_SUDO_PASSWORD


RUNTIME_SETTINGS = RuntimeSettings()

BANK_AUDIT_CODES = {
    "CASYS/STOPANSKA": "OPNBISOCAS01",
    "CASYS/FIBANK": "OPNBISOCAS01",
    "CASYS/RUBICON": "OPNBISOCAS01",
    "AKTIF/BKT": "OPNBISOBKT01",
    "EURONET/OTP": "OPNRENOTP01",
    "NEXI/ALPHA": "OPNBISOA01",
    "BORICA/PROCREDIT": "OPNWAY4B01",
    "NBG": "OPNWAY4N01",
    "EUROBANK": "OPNBISOE01",
    "COSMOTE/NEXI": "OPNBISOC01",
}
BANKS_BY_AUDIT_CODE: dict[str, list[str]] = defaultdict(list)
for bank_name, audit_code in BANK_AUDIT_CODES.items():
    BANKS_BY_AUDIT_CODE[audit_code].append(bank_name)

BANK_ACQUIRER_IDS = {
    "CASYS/STOPANSKA": {"021", "031"},
    "CASYS/FIBANK": {"054"},
    "CASYS/RUBICON": {"056"},
    "AKTIF/BKT": {"050", "065", "978", "003723"},
    "EURONET/OTP": {"063", "99999008036"},
    "NEXI/ALPHA": {"075"},
    "BORICA/PROCREDIT": {"077", "078", "2081", "301000", "808018"},
    "NBG": {"011"},
    "EUROBANK": {"006"},
    "COSMOTE/NEXI": {"061"},
}
PROTOCOL_CHOICES = ("SPDH+ISO", "ISO", "SPDH")
PROTOCOL_SUFFIX_BY_CHOICE = {
    "SPDH+ISO": "SPDH_ISO",
    "ISO": "ISO",
    "SPDH": "SPDH",
}
SOURCE_LOG_FOLDER = "Log folder"
SOURCE_SSH_UAT = "SSH/SCP (UAT)"
SOURCE_ENVIRONMENTS = (SOURCE_LOG_FOLDER, SOURCE_SSH_UAT)
DATA_CHOICES = ("Include byte/data", "Exclude byte/data")

MTI_NAMES = {
    "0100": "Authorization_Request",
    "0110": "Authorization_Response",
    "0120": "Authorization_Advice",
    "0121": "Authorization_Advice_Repeat",
    "0130": "Authorization_Advice_Response",
    "0140": "Authorization_Notification",
    "0141": "Authorization_Notification_Ackn",
    "0200": "Financial_Request",
    "0210": "Financial_Response",
    "0220": "Financial_Advice",
    "0221": "Financial_Advice_Repeat",
    "0230": "Financial_Advice_Response",
    "0240": "Financial_Notification",
    "0241": "Financial_Notification_Ackn",
    "0400": "Reversal_Request",
    "0410": "Reversal_Response",
    "0420": "Reversal_Advice",
    "0421": "Reversal_Advice_Repeat",
    "0430": "Reversal_Advice_Response",
    "0440": "Reversal_Notification",
    "0441": "Reversal_Notification_Ackn",
    "0500": "Batch_Upload_File_Action_Request",
    "0510": "Batch_Upload_File_Action_Response",
    "0520": "Batch_Advice",
    "0521": "Batch_Advice_Repeat",
    "0530": "Batch_Advice_Response",
    "0540": "File_Update_Notification",
    "0541": "File_Update_Notification_Ack",
    "0560": "Settlement_Request",
    "0570": "Settlement_Response",
    "0800": "Network_Management_Request_(Echo_Sign-on_Sign-off_Key_Exchange)",
    "0810": "Network_Management_Response",
    "0820": "Network_Management_Advice",
    "0830": "Network_Management_Advice_Response",
    "0840": "Cutover_Notification",
    "0850": "Key_Exchange_Request",
    "0851": "Key_Exchange_Response",
    "0860": "Echo_Test_Request",
    "0861": "Echo_Test_Response",
    "0870": "Sign-on_Request",
    "0871": "Sign-on_Response",
    "0880": "Sign-off_Request",
    "0881": "Sign-off_Response",
    "0900": "Administrative_Request_(Parameter_Download_Key_Management)",
    "0910": "Administrative_Response",
    "0920": "Administrative_Advice",
    "0930": "Administrative_Advice_Response",
    "0940": "Key_Change_Notification",
    "0950": "Security_Module_Synchronization",
    "0960": "Network_Time_Sync_Parameter_Distribution",
    "1000": "File_Action_Request",
    "1010": "File_Action_Response",
    "1020": "File_Upload_Request",
    "1030": "File_Upload_Response",
    "1100": "Parameter_Download_Request",
    "1110": "Parameter_Download_Response",
    "6000": "Terminal_Initialization_Proprietary_Setup",
    "6100": "Host_Diagnostic_Proprietary_Status",
    "6200": "Software_Update_Custom_Operation",
    "9999": "Undefined_Reserved_Proprietary_MTI",
    "7080": "Echo_Test_Request",
    "9081": "Echo_Test_Response",
    "6001": "Generate_Key",
    "4842": "Call_Data_Logger",
    "6034": "Verify_MAC_Msg_From_PoS",
    "4530": "Financial_Processing",
    "6022": "Generate_MAC_To_POS",
    "4850": "Close_Batch",
}

TANGO_TRANSACTION_MTI_NAMES = {
    "4013": "Pre-auth_Request",
    "8707": "Pre-auth_Request_Reversal",
    "4530": "Purchase",
    "4546": "Purchase_Reversal",
    "4531": "Cash_Advance",
    "4547": "Cash_Advance_Reversal",
    "4533": "Purchase_with_Cashback",
    "4549": "Purchase_with_Cashback_Reversal",
    "4534": "Refund",
    "5251": "Refund_Reversal",
    "4538": "Financial_Purchase_Advice",
    "4558": "Financial_Purchase_Advice_Reversal",
    "4554": "Purchase_Void",
    "4581": "Purchase_Void_Reversal",
    "4555": "Refund_Void",
    "4582": "Refund_Void_Reversal",
    "4557": "Purchase_with_Cashback_Void",
    "4583": "Purchase_with_Cashback_Void_Reversal",
    "4559": "Cash_Advance_Void",
    "4584": "Cash_Advance_Void_Reversal",
    "5109": "Debit_Adjustment",
    "5259": "Debit_Adjustment_Reversal",
    "5110": "Credit_Adjustment",
    "5260": "Credit_Adjustment_Reversal",
    "8706": "Pre-auth_Completion",
    "8705": "Pre-auth_Completion_Reversal",
    "8760": "Pre-auth_Void",
    "8763": "Pre-auth_Void_Reversal",
    "4850": "Close_Batch",
}

ISO_RC_NAMES = {
    "00": "Approved",
    "01": "Refer_to_card_issuer",
    "03": "Invalid_merchant",
    "04": "Pick_up_card",
    "05": "Do_not_honor",
    "12": "Invalid_transaction",
    "13": "Invalid_amount",
    "14": "Invalid_card_number",
    "30": "Format_error",
    "41": "Lost_card",
    "43": "Stolen_card",
    "51": "Insufficient_funds",
    "54": "Expired_card",
    "55": "Incorrect_PIN",
    "56": "No_card_record",
    "57": "Transaction_not_permitted_to_cardholder",
    "58": "Transaction_not_permitted_to_terminal",
    "61": "Exceeds_withdrawal_limit",
    "62": "Restricted_card",
    "65": "Exceeds_withdrawal_frequency",
    "68": "Response_received_too_late",
    "75": "PIN_tries_exceeded",
    "78": "No_account",
    "86": "PIN_validation_not_possible",
    "91": "Issuer_or_switch_unavailable",
    "94": "Duplicate_transmission",
    "96": "System_malfunction",
}

SPDH_RC_NAMES = {
    "000": "Approved",
    "050": "General",
    "051": "Expired card",
    "052": "Number of PIN tries exceeded",
    "053": "No sharing allowed",
    "054": "No security module",
    "055": "Invalid transaction",
    "056": "Transaction not supported by institution",
    "057": "Lost or stolen card",
    "059": "Invalid card status",
    "060": "Account not found in cardholder database",
    "061": "Positive balance account record not found",
    "062": "Positive balance account update error",
    "063": "Invalid authorization type in institution database",
    "064": "Bad track information",
    "065": "Adjustment not allowed in institution database",
    "066": "Invalid credit/cash advance increment",
    "067": "Invalid transaction date",
    "068": "Transaction log file error",
    "069": "Bad message edit",
    "070": "No institution database record",
    "071": "Invalid routing to host application",
    "072": "Card or national negative file",
    "073": "Invalid host authorization service",
    "074": "Unable to authorize",
    "075": "Invalid PAN length",
    "076": "Insufficient funds in positive balance account",
    "077": "Pre-authorization full",
    "078": "Duplicate transaction received",
    "079": "Maximum online refund reached",
    "080": "Maximum offline refund reached",
    "081": "Maximum credit per refund reached",
    "082": "Maximum number of times used",
    "083": "Maximum credit reached",
    "084": "Customer selected negative card file reason",
    "085": "History not allowed - no balances",
    "086": "Over floor limit",
    "087": "Maximum number refund credits reached",
    "088": "Place call",
    "089": "Card status equals 0 (inactive) or 9 (closed)",
    "090": "Referral file full",
    "091": "Problem accessing negative card file",
    "092": "Absence less than minimum",
    "093": "Delinquent",
    "094": "Over limit table or exceeds annual amount",
    "095": "Amount over maximum",
    "096": "Strong customer authentication (SCA) required",
    "097": "Mod 10 check",
    "098": "Force post",
    "099": "Could not access positive balance account in database",
    "100": "Unable to process transaction",
    "101": "Unable to authorize - issue call",
    "102": "Call",
    "103": "Problem accessing negative card file",
    "104": "Problem accessing cardholder account",
    "105": "Card not supported",
    "106": "Amount over maximum",
    "107": "Over daily limit",
    "108": "Card authorization parameters not found",
    "109": "Audience less than minimum",
    "110": "Number times used",
    "111": "Delinquent",
    "112": "Over limit table",
    "113": "Timeout",
    "114": "Transaction log file full",
    "120": "Problem accessing cardholder usage accumulation data",
    "121": "Problem accessing administrative card data",
    "122": "Unable to validate PIN/security module is bad",
    "130": "Cryptogram verification failure referral",
    "131": "Card verification results (CVR) referral",
    "132": "Terminal verification results (TVR) referral",
    "133": "Reason online code referral",
    "134": "Fallback referral",
    "200": "Invalid account",
    "201": "Incorrect PIN",
    "202": "Cash advance less than minimum",
    "203": "Administrative card needed",
    "204": "Enter lesser amount",
    "205": "Invalid advance amount",
    "206": "Invalid expiration date",
    "251": "Cash-back limit exceeded",
    "400": "Cryptogram verification failure decline",
    "401": "Hardware security module parameter error",
    "402": "Hardware security module failure",
    "403": "Impacted circuit card key information not found",
    "404": "Issuer application counter (IATC) check failure",
    "405": "Card verification results (CVR) decline",
    "406": "Terminal verification results (TVR) decline",
    "407": "Reason online code decline",
    "408": "Fallback decline",
    "500": "Administrative card not allowed",
    "501": "Administrative transactions not supported",
    "800": "Host not responding / Timeout",
    "811": "Duplicate transaction",
    "878": "Incorrect PIN length error",
    "888": "MAC communications key (KM/AC) synchronization error",
    "889": "Invalid MAC",
    "899": "Sequence error resync",
    "900": "Number of PIN tries exceeded",
    "901": "Expired card",
    "902": "Negative card file capture code",
    "903": "Card status is 3 (stolen)",
    "904": "Hardware security module unavailable",
    "905": "Number times used exceeded",
    "906": "Delinquent",
    "907": "Over limit table",
    "908": "Amount over maximum",
    "909": "Capture",
    "910": "Cryptogram verification failure capture",
    "911": "Card verification results (CVR) capture",
    "912": "Terminal verification results (TVR) capture",
    "950": "Administrative card not allowed",
    "951": "Administrative transactions not supported",
    "952": "Administrative request out of window",
    "953": "Approved admin request anytime",
    "954": "Advance less than minimum",
    "955": "Chargeback - customer file updated",
    "956": "Chargeback - customer file not updated, acquirer not found",
    "957": "Chargeback - incorrect print receipt",
    "958": "Chargeback - incorrect response code or card prefix configuration",
    "960": "Chargeback - approved customer file not updated",
    "961": "Chargeback - approved customer file not updated, acquirer not found",
    "962": "Chargeback - accepted incorrect presentation",
}

